name: muscular_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy<2          # ADD THIS: Essential to prevent the Whisper/Numba crash
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - fastapi
  - uvicorn
  - openai-whisper
  - python-multipart
  - requests
  - pyperclip
  - ffmpeg
  - pip
  - pip:
      - pygetwindow
      - pyautogui